version: '3.7'

services:
  jamiya:
    image: jamiya-frontend
    container_name: jamiya-frontend
    build: .
    volumes:
      - '.:/usr/src/jamiya-frontend'
      - '/usr/src/jamiya-frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
